=== S3ll4rd0/Ejercicio-XML-DTD/Practica 1 - XML/practice1.dtd
<!ELEMENT Sign-In-Hottie-Kitties (User, E-Mail, Human-Data, Kitties) >
<!ELEMENT User (Nickname, Password, Repeat-Password) >
    <!ELEMENT Nickname (#PCDATA) >
    <!ELEMENT Password (#PCDATA) >
    <!ELEMENT Repeat-Password (#PCDATA) >

    <!ATTLIST Nickname Nick NMTOKEN #REQUIRED >
    <!ATTLIST Password Pass NMTOKEN #REQUIRED >
    <!ATTLIST Repeat-Password Pass NMTOKEN #REQUIRED >

<!ELEMENT E-Mail (Email, Repeat-Email) >
    <!ELEMENT Email (#PCDATA) >
    <!ELEMENT Repeat-Email (#PCDATA) >

    <!-- QuerÃ­a poner esto con NMTOKEN para que no deje espacios -->
    <!-- en blanco en el e-mail, pero me da error, no se porque motivo -->
    <!ATTLIST Email Mail CDATA #REQUIRED >
    <!ATTLIST Repeat-Email Mail CDATA #REQUIRED >

<!ELEMENT Human-Data (Full-Name, Birth-Date, Gender) >
    <!ELEMENT Full-Name (#PCDATA) >
    <!ELEMENT Birth-Date (#PCDATA) >
    <!ELEMENT Gender (#PCDATA) >

    <!ATTLIST Full-Name Name CDATA #REQUIRED >
    <!ATTLIST Birth-Date Day CDATA #REQUIRED >
    <!ATTLIST Birth-Date Month CDATA #REQUIRED >
    <!ATTLIST Birth-Date Year CDATA #REQUIRED >
    <!ATTLIST Gender Type (Male|Female|Undeterminated|Non-binary|Kitty) #REQUIRED >

<!ELEMENT Kitties (How-Many-Kitties) >
    <!ELEMENT How-Many-Kitties (#PCDATA) >

    <!ATTLIST How-Many-Kitties Cats (One|Two|More-Than|I-Want-One|Unanswered) #REQUIRED >

=== S3ll4rd0/Ejercicio-XML-DTD/Practica 1 - XML/Practice1.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE Sign-In-Hottie-Kitties SYSTEM "practice1.dtd">

<!-- Root: Sign-In-Hottie-Kitties -->
<Sign-In-Hottie-Kitties>

    <!-- The user data to login -->
    <User>
        <Nickname Nick="OnlyOneWord">S3ll4rd0</Nickname>
        <Password Pass="P4s2W0rD">iAmTheStrongestPasswordEver</Password>
        <Repeat-Password Pass="P4s2W0rD">Claim1234AsAStrongAndSecurePassword</Repeat-Password>
    </User>

    <!-- Email from the user -->
    <E-Mail>
        <Email Mail="e.mail@service.com">tonet.sellardo@gmail.com</Email>
        <Repeat-Email Mail="e.mail@service.com">tonet.sellardo@gmail.com</Repeat-Email>
    </E-Mail>

    <!-- Complete data from the user -->
    <Human-Data>
        <Full-Name Name="Antonio Salmerón">Antonio Nicolás Salmerón Rubio</Full-Name>
        <Birth-Date Day="30" Month="10" Year="1991">30/10/1991</Birth-Date>
        <Gender Type="Male">Male</Gender>
    </Human-Data>

    <!-- How many cats the user has -->
    <Kitties>
        <How-Many-Kitties Cats="One">Two</How-Many-Kitties>
    </Kitties>

</Sign-In-Hottie-Kitties>
