=== S3ll4rd0/Ejercicio-XML-DTD/XML - DTD Delivery/Exercise1.dtd
<!ELEMENT Solicitud-de-Acceso (Datos-Solicitante, Tipo-Acceso-Solicitante, Solicitud-Alumno+, Fecha)>

<!ELEMENT Datos-Solicitante (Documento-Nacional-Identidad, Nombre, Apellidos)>
    <!ELEMENT Documento-Nacional-Identidad (#PCDATA)>
    <!ELEMENT Nombre (#PCDATA)>
    <!ELEMENT Apellidos (#PCDATA)>

<!ATTLIST Documento-Nacional-Identidad Identificador ID #REQUIRED>

<!ELEMENT Tipo-Acceso-Solicitante (Correo-Electronico)>
    <!ELEMENT Correo-Electronico (#PCDATA)>

<!ELEMENT Solicitud-Alumno (Alumno, Curso)>
    <!ELEMENT Alumno (#PCDATA)>
    <!ELEMENT Curso (#PCDATA)>


<!ELEMENT Fecha (Fecha-Completa, Dia-Nominal, Dia-Numerico, Mes, Año, Localidad)>
    <!ELEMENT Fecha-Completa (#PCDATA)>
    <!ELEMENT Dia-Nominal (#PCDATA)>
    <!ELEMENT Dia-Numerico (#PCDATA)>
    <!ELEMENT Mes (#PCDATA)>
    <!ELEMENT Año (#PCDATA)>
    <!ELEMENT Localidad (#PCDATA)>

    <!ATTLIST Fecha-Completa dia CDATA #IMPLIED>
    <!ATTLIST Fecha-Completa mes (OCTUBRE|NOVIEMBRE) #IMPLIED>
    <!ATTLIST Fecha-Completa año CDATA #IMPLIED>

=== S3ll4rd0/Ejercicio-XML-DTD/XML - DTD Delivery/Exercise1.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE Solicitud-de-Acceso SYSTEM "Exercise1.dtd">

<Solicitud-de-Acceso>

    <Datos-Solicitante>
        <Documento-Nacional-Identidad Identificador="W48679042">
            48679042W</Documento-Nacional-Identidad>
        <Nombre>Antonio Nicolás</Nombre>
        <Apellidos>Salmerón Rubio</Apellidos>
    </Datos-Solicitante>

    <Tipo-Acceso-Solicitante>
       <Correo-Electronico>tonet.sellardo@gmail.com</Correo-Electronico> 
    </Tipo-Acceso-Solicitante>

    <Solicitud-Alumno>
        <Alumno>Antonio Nicolás Salmerón Rubio</Alumno>
        <Curso>1º DAW Semi</Curso>
    </Solicitud-Alumno>

    <Solicitud-Alumno>
        <Alumno>Antonio Nicolás Salmerón Rubio</Alumno>
        <Curso>1º DAW Semi</Curso>
    </Solicitud-Alumno>

    <Solicitud-Alumno>
        <Alumno>Antonio Nicolás Salmerón Rubio</Alumno>
        <Curso>1º DAW Semi</Curso>
    </Solicitud-Alumno>

    <Solicitud-Alumno>
        <Alumno>Antonio Nicolás Salmerón Rubio</Alumno>
        <Curso>1º DAW Semi</Curso>
    </Solicitud-Alumno>

    <Fecha>
        <Fecha-Completa dia="09" mes="OCTUBRE" año="2022">
            </Fecha-Completa>
        <Dia-Nominal>Lunes</Dia-Nominal>
        <Dia-Numerico>09</Dia-Numerico>
        <Mes>05</Mes>
        <Año>2022</Año>
        <Localidad>Benidorm</Localidad>
    </Fecha>

</Solicitud-de-Acceso>
